[[redirects]]
  from = "/studio"
  to = "https://miradorstudio.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/studio/*"
  to = "https://miradorstudio.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/sanity/*"
  to = "https://miradorstudio.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/cms/*"
  to = "https://miradorstudio.netlify.app/"
  status = 301
  force = true