[[redirects]]
  from = "/studio"
  to = "https://miradorstudio.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/studio/*"
  to = "https://miradorstudio.netlify.app/"
  status = 301
  force = true