[[redirects]]
  from = "/studio"
  to = "https://miradorstudio.netlify.app/"
  status = 200
  force = true

[[redirects]]
  from = "/studio/*"
  to = "https://miradorstudio.netlify.app/:splat"
  status = 200
  force = true